name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x map-sample/gradlew && chmod +x navigation-sample/gradlew 
    - name: Build map-sample with Gradle
      run: cd map-sample && ./gradlew build
    - name: Build navigation-sample with Gradle
      run: cd navigation-sample && ./gradlew build
